In [55]:
import numpy as np
import numpy.char as char

In [2]:
list = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]

In [3]:
arr = np.array(list)

In [4]:
arr_times_4 = arr*4
print(arr_times_4)

[ 80 108  36  48 124  68  16 200 156 140]


In [5]:
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))


24.4
23.5
13.828955130450023


In [11]:
np.argmin(arr)


np.int64(6)

In [13]:
print(np.int64(6))

6


In [14]:
np.min(arr)

np.int64(4)

In [9]:
print(np.int64(50))

50


In [10]:
np.argmax(arr)

np.int64(7)

In [12]:
print(np.int64(7))

7


In [15]:
np.max(arr)

np.int64(50)

In [16]:
print(np.int64(4))

4


In [26]:
array_over_twenty = arr[arr > 20]
print(array_over_twenty)

[27 31 50 39 35]


In [29]:
matrix = [
[5, 12, 17, 9],
[8, 21, 14, 3],
[6, 13, 19, 11]
]

np_matrix = np.array(matrix)
print(np_matrix)
#3 rows and 4 columns

[[ 5 12 17  9]
 [ 8 21 14  3]
 [ 6 13 19 11]]


In [38]:
print(np_matrix[:, 2])
print(np_matrix[1,:])

[136 112 152]
[ 64 168 112  24]


In [36]:
np_matrix = np_matrix * 2
print(np_matrix)

[[ 40  96 136  72]
 [ 64 168 112  24]
 [ 48 104 152  88]]


In [43]:
print(np.mean(np_matrix[1]))

92.0


In [44]:
print(np.mean(np_matrix))

92.0


In [50]:
print(np.max(np_matrix[0,:]))
print(np.max(np_matrix[1,:]))
print(np.max(np_matrix[2,:]))

136
168
152


In [52]:
print(np.min(np_matrix[:,0]))
print(np.min(np_matrix[:,1]))
print(np.min(np_matrix[:,2]))
print(np.min(np_matrix[:,3]))

40
96
112
24


In [61]:
flat_matrix = np_matrix.flatten()
print(flat_matrix)
#The matrix got turned into an array, it is one row

[ 40  96 136  72  64 168 112  24  48 104 152  88]


In [69]:
min_flat_index = np.argmin(np_matrix)
max_flat_index = np.argmax(np_matrix)

In [70]:
min_coords = np.unravel_index(min_flat_index, np_matrix.shape)
max_coords = np.unravel_index(max_flat_index, np_matrix.shape)

In [71]:
greater_than_15 = np_matrix[np_matrix > 15]

In [72]:
sorted_by_row = np.sort(np_matrix, axis=1)
print(sorted_by_row)

[[ 40  72  96 136]
 [ 24  64 112 168]
 [ 48  88 104 152]]


In [75]:
arr = np.array([
[2, 3, 5],
[14, 6, 8],
[11, 13, 17],
[7, 10, 13]
])
# ---Brainstorm---
#need funciton to check a # is prime and then another one to check the number against the array
# 2 is the only even prime number.
# need to check for odd divisors from 3 up to the square root of n.
# if no divisors are found, its prime.
def is_prime(n):
    if n <= 1:
        return False
    if n == 2:
        return True
    if n % 2 == 0:
        return False
    for i in range(3, int(n**0.5) + 1, 2):
        if n % i == 0:
            return False
    return True

# 1. Create a vectorized version of is_prime function to let NumPy  apply the Python function to every single element in the array efficiently.
# 2. apply the vectorized function to the entire array which creates a new array of the same shape with bool values.
# 3. then check axis = 1 (rpw) for at least one true value and collapse the 2D mask into a 1D mask for the rows.
# 4. Use this 1D boolean mask to select rows from the original array.

def find_prime_rows(arr):
    
    
    vectorized_is_prime = np.vectorize(is_prime)

    prime_mask = vectorized_is_prime(arr)

    row_has_prime = np.any(prime_mask, axis=1)

    filtered_array = arr[row_has_prime]
    
    return filtered_array

prime_rows = find_prime_rows(arr)
print(prime_rows)
print(arr)
        

[[ 2  3  5]
 [11 13 17]
 [ 7 10 13]]
[[ 2  3  5]
 [14  6  8]
 [11 13 17]
 [ 7 10 13]]


In [90]:
def make_grid():
    return np.zeros((8, 8))    

grid = make_grid()
print(grid)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [92]:
def make_board():
    checkerboard = np.zeros((8, 8), dtype = int)
    checkerboard[::2, 1::2] = 1 #even rows and odd columns get a 1
    checkerboard[1::2, ::2] = 1 #even columns and odd rows get a 1
    return checkerboard

checkerboard = make_board()
print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [104]:
def reverse_board():
    checkerboard = np.zeros((8, 8), dtype = int)
    checkerboard[::2, ::2] = 1
    checkerboard[1::2, 1::2] = 1
    return checkerboard

checkerboard = reverse_board()
print(checkerboard)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [105]:
def expand(s, num_spaces):
    spacer = " " * num_spaces #spacer literally multiplies spacebar by input #
    
    return spacer.join(s) # join every character in the string w/ the spacer

# Create the main 'expansion' function by vectorizing the helper which tells numpy to apply the expand function
# to every element in the input array.
expansion = np.vectorize(expand)
string = np.array(['where','are','you','going?'])
expanded_1 = expansion(string, 1)
print(expanded_1)
expanded_10 = expansion(string, 10)
print(expanded_10)

['w h e r e' 'a r e' 'y o u' 'g o i n g ?']
['w          h          e          r          e' 'a          r          e'
 'y          o          u'
 'g          o          i          n          g          ?']


In [107]:
import numpy as np

def secondBrightest(stars_array):
  sorted_stars = np.sort(stars_array, axis=1)
  return sorted_stars[:, -2]

np.random.seed(123)
stars = np.random.randint(500, 2000, (5, 5))

print(stars)

result = secondBrightest(stars)

print(result)

[[1889 1906 1846 1622 1541]
 [ 606 1647 1738  596  613]
 [1138  547  573 1442  724]
 [ 611 1933 1863 1346 1777]
 [ 920 1108 1732 1592  951]]
[1889 1647 1138 1863 1592]
